### ISSUE TITLE
OSX and Homebrew

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#10]
We could use help building and distributing Faktory via Homebrew.  This would make basic usage on OSX much, much easier.  Anyone know how to do this?

**Comment by byt3smith** [comment]
They have pretty solid instructions:
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by nicolas-besnard** [comment]
What about Docker ?

**Comment by mperham** [comment]
@nicolas-besnard https://github.com/contribsys/faktory/pull/20

**Comment by nycdavid** [comment]
@mperham I can take a stab at this and report back 👍

**Comment by squarism** [comment]
For homebrew formulas, it's what @byt3smith linked.  You just need to decide how you want to build the binaries.  I'd probably suggest [ghr](https://github.com/tcnksm/ghr) for right now.

**Option 1**
What you (Mike) would do as the author is remember (manually) to upload the binary from your mac on release or tag.  GHR can be setup easily to help with this and I've done it before.  This would save you from the complexity of the next option ...

Once you have it setup it's like: `ghr v0.6.0 faktory`.  You just need to setup some OAUTH tokens.
You could also update your `Makefile` to output to an ignored bin directory to make this work a bit better with `ghr` because `ghr` takes a file or a path of files but not a list of files.  But it seems to be ok with updating a release.  For example:

```
ghr v0.6.0 faktory
ghr v0.6.0 faktory-cli
WARNING: found release (v0.6.0). Use existing one.--> Uploading:      faktory-cli
```
Because this project has two binaries.

**Option 2**
Find a CI option.  Since a travis config is already done from #33, and it's Linux, you probably can't do it from Travis.  I don't know how to do multi-environment (OS's) builds in Travis.  CircleCI 2.0 seems to have killed their OSX env (idk) because they are going full docker.  I had a travis.yml config started to do OSX builds but the dev loop is really slow because I'm on a free tier.
You could pay for [buildkite](https://buildkite.com/) or something.

The nice thing is that ghr can be used with CI.  So once you have ghr setup, you can just have binaries uploaded whenever there's a commit to master or a tag to master?  I don't know how you'd want this workflow setup but a post hooks for CI services are detailed on the [ghr wiki](https://github.com/tcnksm/ghr/wiki/Integrate-ghr-with-CI-as-a-Service).

Cheers.

**Comment by nycdavid** [comment]
Ah interesting! I forked the homebrew-core repo and linked it to the Faktory tarball stored on git, so I must be attempting the last method you outlined (getting it into the official repo).

I haven't gotten very far yet, but the work is here: https://github.com/nycdavid/homebrew-core/tree/faktory

The ghr method seems interesting, I'd like to look into. Not sure how far I'd get, since I'm not the owner of the repo... 🤔

**Comment by andrewstucki** [comment]
@squarism The process for doing a travis build on OSX should be nearly identical, you just need to add osx into the build matrix and then conditionally run pieces of your test, like [this](https://docs.travis-ci.com/user/multi-os/#Example-Multi-OS-Build-Matrix).

@nycdavid if you do write the Homebrew formula I think you'll probably have some magic to do with the gopath to make sure it builds from the right dependencies. Looking at another go project like [nsq](https://github.com/Homebrew/homebrew-core/blob/master/Formula/nsq.rb) may or may not help.

**Comment by nycdavid** [comment]
@andrewstucki Ah okay, thanks for the tip! 🙂

**Comment by squarism** [comment]
@andrewstucki thanks!

**Comment by andrewstucki** [comment]
@nycdavid Just a heads up, I took a look at the implementation this would need for homebrew and realized that building the dependencies for the generation binaries are a bit more complex than I would have thought, so I just took care of it: https://github.com/Homebrew/homebrew-core/pull/19897/files

**Comment by nycdavid** [comment]
@andrewstucki Oh nice, looks good 👍

**Comment by mperham** [comment]
wow 👏

**Comment by andrewstucki** [comment]
@mperham not sure if/when this will get merged, so just in case it doesn't (due to the fact that faktory isn't fully stable?), feel free to grab the above code and throw it into a contribsys tap -- should at least let people use the formula in a relatively straightforward way.

**Comment by mperham** [comment]
@andrewstucki Looks like if I create contribsys/homebrew-faktory and we drop the right formulae there, people can access it with brew tab contribsys/faktory?

**Comment by mperham** [comment]
As much as I want the entire world to start working with it tomorrow, I would avoid official brew releases until 1.0.  Faktory is still young and not stable yet.

**Comment by andrewstucki** [comment]
I believe so. It's been awhile since I've used a third-party tap, but I think just dropping the `faktory.rb` that I submitted the PR for into the top-level of a repo like `github.com/contribsys/homebrew` would allow people to use it via `brew tap contribsys/homebrew && brew install faktory` per the directions @squarism  outlined above.

**Comment by andrewstucki** [comment]
@mperham I'll mention in the PR that still talking with the primary author of the project about whether he wants the formula in core or is fine creating his own tap.

**Comment by mperham** [comment]
Thank you all, Homebrew is live!

https://github.com/contribsys/faktory/wiki/Installation#osx
