### ISSUE TITLE
Anything similar to Sidekiqs retries_exhausted?

### ISSUE THREAD

**Issue by jagthedrummer** [contribsys/faktory#137]
Just curious if there's anything comparable to the `retries_exhausted` feature of Sidekiq, described here: https://github.com/mperham/sidekiq/wiki/Error-Handling

**Comment by mperham** [comment]
This is one of those features that is specific to Sidekiq's architecture and would need to be redesigned for Faktory.  Since the Faktory worker process doesn't know anything about retries (it just blindly reports success/failure), there's no way right now for Faktory to run a piece of code within the worker process without further refining the protocol.

**Comment by jagthedrummer** [comment]
That's kinda what I suspected, thanks for confirmation.
