### ISSUE TITLE
Question : Can a reservation be extended by a worker

### ISSUE THREAD

**Issue by karlmutch** [contribsys/faktory#146]
Can a worker extend the reservation on a job after the job has been FETCH'ed and before it is ACK'ed or FAIL'ed ?

The motivation is that this would help to have a shorter re-queue time for very long running jobs.

Thanks,
Karl

**Comment by mperham** [comment]
You can't extend it but you can lengthen the reservation with `"reserve_for": XXXX` in the job payload, where XXXX is an integer number of seconds, for longer jobs.  In Ruby:

```ruby
class LongJob
  include Faktory::Job
  faktory_options reserve_for: 3.hours
```

**Comment by liftM** [comment]
Can I lengthen this reservation after I've `FETCH`ed the job?

My use case is that I have potentially long-running jobs, most of which are short (minutes) but some of which can get pretty long (hours). I'd like to be able to re-reserve the job as long as my worker is running, but I don't want an infinite timeout because my workers may die in the middle of processing.

**Comment by mperham** [comment]
There's no way to modify the reservation once fetch'd but I would be open to a PR so a worker to allow this.

**Comment by diwu1989** [comment]
I'm interested in an API to do this as well.
Example usecase:
I pull data from O365, and normally the API doesn't throttle, but when it does throttle, my client has to sleep for a bit and then retry. Part of the work would have been done already, so it's better to be able to explicitly extend the job continuously as it wait for the throttle to end.

**Comment by mperham** [comment]
As of 2020, Faktory Enterprise allows a job to extend its own reservation thru the Job Tracking feature using the `reserve_until` attribute:

https://github.com/contribsys/faktory/wiki/Ent-Tracking
