### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by Diggsey** [contribsys/faktory#149]
I currently use a custom job queue built on top of postgres (I have had bad experiences with job queues that lose message for various reasons, either because their transactional semantics are broken, or because the storage system is not as well tested as your average database).

The use of RocksDB as a storage layer makes this project look very promising, and the extensive introspection functionality is another thing I've greatly missed from other job queues.

Here are some features I think are missing from faktory that I currently rely on:

- Ordering constraints

Sometimes you need some jobs to happen in order. The way this works is that each job can optionally be tagged with a "channel" identifier. Jobs queued to a channel do not start processing until all jobs before them in the same channel have been ACKed.

This is useful for delivering web-hooks: external systems often expect to receive events in order, and the channels mechanism allows each system to operate on a different channel, allowing as much parallelism as possible.

- "keep alive" messages

It may be difficult to select a single timeout value for a job which may take an unpredictable amount of time - it would be useful if workers could send "keep alive" messages to indicate that they are still processing a job. The job is only re-queued if no "keep alive" messages are received within the timeout.

- Different backends

RocksDB is another storage system to pay for, backup, and otherwise maintain. Other backends (particularly postgres) would reduce a lot of the up front cost to using this system. It also means you can take a backup and get a consistent snapshot of both your records *and* your in-flight jobs.

As an addition to this feature - it would be neat if you could piggyback on existing connections to the backend, at least for queuing new jobs - for example, being able to add a job to the queue as part of a larger transaction, such that if the transaction is rolled back, the job is never added.

**Comment by espadrine** [comment]
> Different backends

RocksDB is also a SPOF. The **expected job loss in a year** is roughly AFR×J, where AFR is the drive's annualized failure rate, and J is the average number of jobs.

Given an SSD with a [0.7%](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/08/a7-narayanan.pdf) AFR and an average number of jobs at 10k, you should expect to lose 70 jobs a year.

(It can also lead to **unavailability**, which could be solved by setting up a streaming replication to a hot failover server, but it is complex to put in place.)

The good news is the open-sourcing of [FoundationDB][], a key-value store (just like RocksDB) that is distributed (to ensure availability), replicated (to reduce the probability of loss from a drive failure), and backed by Apple.

[FoundationDB]: https://www.foundationdb.org/

I would be interested in seeing whether I could add support for FoundationDB as a backend.
What are your thoughts on this?
Would it have a chance to get merged if I worked on a patch?

**Comment by mperham** [comment]
@espadrine That adds a very complex dependency that no one knows how to install or manage in production.  The benefit of RocksDB is that it is completely embedded within Faktory, the user does not need to install or manage anything.  I would be very happy if someone can integrate a KV store that has replication but I don't want Cassandra/Foundation/etc with its huge footprint.

**Comment by espadrine** [comment]
I agree. Having RocksDB is a solid, dead-simple *default* backend.

When the *probability of job loss* needs to be lowered, or when the *throughput* soars, a Faktory user will need something bigger. I see FoundationDB as the best replicated KV store they can switch to, when outgrowing RocksDB.

Faktory would only have the [thin client](https://github.com/apple/foundationdb/tree/master/bindings/go/src/fdb) in its binary, while the FoundationDB system would be separately managed by the user on other machines. Connecting Faktory to the DB machines is [detailed here](https://godoc.org/github.com/apple/foundationdb/bindings/go/src/fdb).

To use FoundationDB instead of RocksDB, the user would need to set the `FAKTORY_FDB_CLUSTER_FILE` environment variable, which points to a metadata file generated by a FoundationDB server.

With respect to Cassandra vs. FoundationDB, they are subtly different (Cassandra is an AP system, while FoundationDB is CP, in the CAP sense, which makes FoundationDB closer to the way RocksDB works).
