### ISSUE TITLE
Faktory and Heroku

### ISSUE THREAD

**Issue by taylorbrooks** [contribsys/faktory#15]
It would be awesome to use Faktory on Heroku. No idea what's involved in doing this, mainly opening this issue as a placeholder.

**Comment by mperham** [comment]
👍

**Comment by mperham** [comment]
We'd need to build a Linux binary ([pretty easy](https://github.com/contribsys/faktory/wiki/Development#setup)) and a Heroku buildpack (never done this) to package that binary to run on Heroku.

**Comment by mperham** [comment]
With more thought, unfortunately it's not easy today.  There are more concerns:

1. Password.  Since you are starting a network service, you need to have a password on it.  You can use an env var or place the password in /etc/faktory/password, e.g. `FAKTORY_PASSWORD=password123 /usr/local/bin/faktory -b :7419 ...`
2. You'll want TLS so you'll need a certificate so Faktory can encrypt all communication between the worker processes and faktory.  See the Security wiki page.
3. You'll need to start a worker process as part of your application, just like you start a Sidekiq process today: `bundle exec faktory-worker`.
3. Finally you'll need to configure the worker process to access Faktory by setting FAKTORY_URL:

heroku config:set FAKTORY_URL=tcp://:password123@faktory.example.com:7419

Note that most of the complexity here is security.  This is where a Faktory SaaS would add value and solve these steps for you. @mbuckbee is an expert here.

**Comment by Skeyelab** [comment]
@mperham - your readme says Faktory is better than Sidekiq because all of Sidekiq's data travels across the network.  How is Faktory any different?  You run Faktory on one machine and the app server on a different machine.  They communicate over the network.

**Comment by mperham** [comment]
Faktory can implement features internally because the feature code and storage are all in the same server process.  The Faktory worker process, which is over the network, doesn't need to implement the feature at all.  With Sidekiq features, the **Redis datastore** is over the network and so data lookups require the network.

**Comment by danp** [comment]
@mperham perhaps I've misunderstood but isn't all data currently persisted in the server process or on disk close to it? Won't that break with dyno restarts?

**Comment by danp** [comment]
Or maybe based on the steps above the assumption is that FAKTORY_URL would point to something outside the app/Heroku?

**Comment by mperham** [comment]
@danp You're right, Faktory persists state so it can't be on a dyno.  FAKTORY_PROVIDER/FAKTORY_URL are designed so you can point the client/worker to wherever you locate the server.

**Comment by mperham** [comment]
The workers are fine for dynos and you can autoscale them as necessary.

**Comment by thebadmonkeydev** [comment]
I'm actually working on a hosted Faktory solution and Heroku addon right now https://www.producthunt.com/upcoming/ack-foundry

Don't have to worry about where to locate those servers if you make me do it :joy:

**Comment by jagthedrummer** [comment]
Oh hey, @jeff-french and I have also started on a similar Faktory-as-a-service offering.

http://konglomerate.io/

**Comment by thebadmonkeydev** [comment]
Great minds, huh?  I'm glad to see the ecosystem growing so quickly (nothing like a little healthy competition, right?)  In the sake of sharing ACK Foundry has it's own landing page now

https://www.ackfoundry.com

@mperham I think this issue can be closed given that the solution is being built outside of Faktory, your call though.

**Comment by dylanjha** [comment]
@thebadmonkeydev @jagthedrummer I'm excited to see both of these! I am _very_ interested in testing this out. I've signed up for updates for both of your project

**Comment by sfcgeorge** [comment]
Data persistence seems to be the only issue with running directly on Heroku, so can't the faktory_redis_dir data directory be configurable to be stored on S3?

**Comment by mperham** [comment]
@sfcgeorge S3 is not a disk, it is cloud storage.  Redis needs local disk.  You can run Faktory on an EC2 instance but yeah, there's not plug and play options on Heroku today.

**Comment by john-griffin** [comment]
Anyone running on heroku yet?
