### ISSUE TITLE
Job priority

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#18]
Can we support simple job prioritization?  Today the queue key in RocksDB is `queueName|index`, we could change the key to be `queueName|priority|index` but that would make it impossible to get the next job as an O(1) operation.  We could use a live cursor that would walk the RocksDB key tree in real-time but I'm not sure of the performance implications.  Other ideas?

**Comment by mperham** [comment]
This makes it impossible to generate the key of the next queue entry for O(1) queue access.

**Comment by andrewstucki** [comment]
What about keeping an in memory priority queue of the cursor pointers based off of priority? It looks like each queue keeps a pointer to the highest and lowest offsets in the queue based off of prefixed keys, incrementing the highest offset on `push` operations and incrementing the lowest on `pop`.

Well, if instead of having a single global pointer to high/low, if you kept a list of pointers sorted by priority then you could still maintain O(1) for `pop` operations (since you'd just grab the lowest offset of the first pointer), while lowering `push` to something like O(log n) due to the need to do some sort of sorted insertion into the priority queue for pointers to new priorities.

Sounds kind of abstract, but basically what I'm thinking would look something like [this snippet.](https://play.golang.org/p/BVY-xrDQ6c)

I'm not 100% sure off the top of my head how this sort of structure would affect in-order scan performance since at that point you'd have to do scan using loops of iterators, but just a thought.

**Comment by andrewstucki** [comment]
@mperham forgot to mention, the nice thing about this type of strategy is that the runtime isn't actually dependent on the number of keys in the persistent queue, but only on the number of priority-tracking elements in the in-memory queue. So, assuming you don't have like 1000000 different priority levels that are all being used at once, this should be very quick for pushes and pops.

The one thing about the code snippet that I'm not sure of are the runtimes around the slice removal/appending, but assuming you use something like a [Brodal Queue](https://en.wikipedia.org/wiki/Brodal_queue) for the in-memory structure, you could get better guarantees around the time each of these operations take.

**Comment by mperham** [comment]
I'm coming around to this idea but I'm not quite sold yet.  For the longest time, I've told people to prioritize via separate queues: critical, default, bulk.  But that doesn't work well if you want to separate jobs into different queues for polyglot reasons: a golang queue, ruby queue, etc based on the targeted worker or if you want to have queues for different features: image_processing, email_outbox, etc.

I would limit priorities to 9: 1-9, with 5 being the default or no stated priority.  There's no need for arbitrary 8-bit or 16-bit values.

In thinking about it, adding job priority affects:

* queue.Init(), Push() and Pop()
* Web UI queue listing, job display

Since we are keeping in-memory structures about the queue contents, we would need to add their creation to the Init() call but this shouldn't be too hard since we already need to do a full queue scan today, however this would require us to decode the JSON for every enqueued job payload in order to read the priority, right?  That's a major downside if the queues are large (which is unusual).

**Comment by andrewstucki** [comment]
For the initial scan I don't think that it would actually be a big deal--because as in the snippet and in your initial idea, the key would have the priority encoded into it--so the process for reconstructing the queue on initialization would involve grabbing all the keys, decoding them to get the priority and sequence, then re-inserting pointer records into the queue based off the highest/lowest discovered (priority, sequence) pair.

For the priority inside of the job payload issue--the only time you should have to deserialize the json to take a look at the priority is in the same place that the json is deserialized already--when issuing a `PUSH` (since the json is decoded to look at which queue to place the job on).

**Comment by mperham** [comment]
Are you suggesting that we’d construct N in memory linked lists per queue with an entry for each job in Rocks? I think this is a reasonable idea, it would make it easy to add a “non-persistent” queue feature too.

**Comment by andrewstucki** [comment]
Not quite sure what you mean by "with an entry for each job" -- but the idea is a linked list/priority queue per rocksDB queue where the entries are structures that handle the offset tracking that is currently done in [this struct](https://github.com/contribsys/faktory/blob/ce97d6779fdcd5072edb422b33e71f8b2edaf5bc/storage/queue_rocksdb.go#L40) with the high and low members.

You would have a structure that looked something like

```
type pointer struct {
  low int64
  high int64
  priority int
}
```

and would change the current structure definition to be something like:

```
type rocksQueue struct {
  ...
  priorities []*pointer
  ...
}
```

**You would have an entry in the slice for each priority level that currently has jobs** and would ensure it using something akin to the algorithm in the snippet above.

This way you don't have to have all the jobs in memory and can still use simple sequence offsets to retrieve your next key in the queue.

**Comment by andrewstucki** [comment]
@mperham: if you're ok with the idea, maybe I can take a stab at this. Would be helpful to have some benchmarking metrics to see how the prioritization affects the speed

**Comment by mperham** [comment]
Sounds great.  It would also be nice to have some idea of memory usage with 1,000,000 jobs enqueued.  The /debug web page has a TotalAlloc memory value that would give a coarse grained ballpark value of Go's total allocated memory.

**Comment by andrewstucki** [comment]
Here you go: #68
