### ISSUE TITLE
Non-embedded Redis

### ISSUE THREAD

**Issue by cjbottaro** [contribsys/faktory#200]
Yo! I noticed there was an old issue about Kubernetes support and ideas. I use/manage 5 Kubernetes clusters in AWS using kops and I think this would make things a lot easier for me...

It would be really nice to point Faktory at an AWS managed instance of Redis. Otherwise, we have to use EBS for persistence. EBS volumes are AZ specific, so that means we would have to make a kops InstanceGroup that only launches EC2 instances in the AZ that the EBS volume is in. Then we'd have to write PodAffinity rules for our Faktory Deployments so that our Faktory Pods end up on instances in the right AZ that can mount the EBS volumes.

If Faktory can use remote Redis, then we just make an ElastiCache instance (or a Redis Kubernetes Service) and then we're free to scatter Faktory pods in our cluster, not caring about what AZ they end up in.

🙏

**Comment by mperham** [comment]
I thought about this but what happens to Faktory when the network latency between Faktory and the Redis instance goes to 10ms or more due to ${RANDOM_NETWORKING_PROBLEM}?  IME that's far more likely than a system failure.  Enforcing Redis on the same machine gives me QoS guarantees.

I envision a future where there is a Faktory SaaS which automatically provides this routing and failover but it isn't here today.
