### ISSUE TITLE
Provide basic job admin commands

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#204]
One major limitation of Faktory vs Sidekiq is Sidekiq's API which allows people to programmatically access and operate on elements within queues and sets.

Design and implement a new set of commands which can page through data structures and perform well-defined actions on the jobs therein.  Example:

```
VIEW [structure] [offset] [pagesize]
> VIEW retries 0 50
{ 
  "elements": [
   { payload1 },
   { payload2 },
   ...
  ]
}
```

For example, with these commands you could build CLI tooling which replicates the Web UI.  Each command could return a JSON blob with a batch of results.

```
KILL [structure] [...JIDs...]
> KILL retries abc123 def456
{ "elements":["abc123"] }
# move these JIDs from the retries set to the dead set, perhaps def456 was not found or had already been processed
```

Actions:

* KILL - moves job from structure to Dead set
* DISCARD - moves job to /dev/null
* ENQUEUE - move job from retries or dead to queue to be processed immediately
* Others?

These commands are not scalable and are designed more for data repair and migration, not for routine application business logic.  Because of this caveat, we might want to namespace them or provide additional access control for them.  You might not want normal business applications to use them directly.

**Comment by jbielick** [comment]
Excellent—these have been _critical_ on several occasions over the years in Sidekiq.

> These commands are not scalable and are designed more for data repair and migration, not for routine application business logic.

Makes perfect sense and I don't think there's much of a way around those constraints without unreasonable tradeoffs.

### Actions

`KILL|DISCARD [structure] [JIDs...]`

The `KILL` seems great—that's exactly how I would have guessed it would be structured. Enqueue is the only one that's a little ambiguous considering `PUSH`. Seems insignificant, but I wonder if something like `REQUEUE`, `REVIVE` or something would be received.

### Clearing queues?

Is `JIDs` in brackets because it's optional? Would not providing a JID discard / kill the whole queue? I could see that being a little bit dangerous if so. Maybe a `*` or something would be a little less user-error-proof? Or maybe there's an entirely separate way to run `Queue#clear`.

### Iterating

I'm sort of just now realizing that sidekiq's implementation of `Queue#each` is a paginated list as well. That's new to me so I'll preface this with: this may work perfectly and there's no issue. 

Personally I've been confused more than a few times when using the Sidekiq API that when I iterated through the queue to "clean it" of certain jobs (poison pills or other) that I often _missed_ items. In fact, it always seemed like I had to iterate 3-4 times before I actually successfully cleaned the (large) queue. I'm guessing this is due to the pagination offset—where workers are popping jobs and the jobs in the queue are shifting downward in position while I'm paging upwards in position (offset). 

I always found that kind of frustrating, but fully understand the tradeoff of a read-only (in this context) queue. I'm wondering what other methods you considered and what the tradeoffs were—I certainly don't want to oversimplify and pretend there's an easier, stable iteration.

Some assumptions and considerations (for my own understanding):

### Paginated, start at 0 index

- Ensures you iterate over the whole queue from start to end
- Has a definite stopping point provided you're not producing new pages of jobs faster than you're iterating and completing them
- O(N) 👍 complexity and alleviated by batching (`LRANGE`)
- In a situation where you're trying to remove poison pill jobs, allows you to race the workers
- If workers are paused, works perfectly fine
- Treats the queue as read-only

### Bad Ideas?

- Paginated, start at last index
- `RPOPLPUSH` to cycle through the whole queue one job at a time (O(1) op, O(N) total time), changing ordering of the queue as new jobs interleave the queue
- Some cursor-based approach? (not possible I'm guessing)

Just thinking out loud a bit.

**Comment by mperham** [comment]
Amazing feedback; I had many of the same thoughts.  ENQUEUE is a poor name.  Iterating is hard when you can't lock the structure and it's actively being mutated.  More to come...

**Comment by jbielick** [comment]
Adding this here for examples from other similar projects:

https://github.com/antirez/disque#main-api

**Comment by jsierles** [comment]
Would this be a first necessary step for monitoring queue lengths? Or can/should this be done directly against Redis?

**Comment by mperham** [comment]
@jsierles You can get the size of all queues by calling the INFO command. https://github.com/contribsys/faktory/wiki/Worker-Lifecycle#information
