### ISSUE TITLE
Monitoring and alerting possibilities

### ISSUE THREAD

**Issue by pbrisbin** [contribsys/faktory#206]
We're in need of a way to fit Faktory job processing into our production monitoring and alerting systems. Concretely, this means metrics in DataDog for (at least): queue lengths, successes, retries, and failures. Ideally, these would be emitted as statsd metrics. This low-level direct reporting would be the best way (IMO) to support the ideas in #188 with entirely external services.

Is there any functionality that could be used to accomplish this that I'm missing? If not, are there any plans to add it?

I thought I remembered hearing that Faktory Pro would support using your own Redis. Among many other benefits that would bring for us, it would allow our own monitoring service for gathering these metrics by looking directly at the Redis data. But I can't find where I saw that, and some on my team suggest it's no longer going to be possible -- is that true?

**Comment by mperham** [comment]
Statsd and Prometheus support are two features I plan to add to Faktory Pro in the next quarter.  The INFO command gives you all you need in a JSON payload.

https://github.com/contribsys/faktory/wiki/Worker-Lifecycle#information

**Comment by pbrisbin** [comment]
> Statsd and Prometheus support are two features I plan to add to Faktory Pro in the next quarter

That's great to hear! Would you be interested in gathering any details about our needs, as input into how you build that?

> The INFO command gives you all you need in a JSON payload

Ah, I was looking for a description of its schema. Thanks. Unfortunately, I can't see how I would get:

- `enqueued` number by Queue
- success/failure counts/rates by Queue and/or Job

---

As an aside (and all due respect as you're far more experienced in this area than I), it strikes me that stats in Faktory in general are very "totals focused", but I find such numbers almost useless for us. The fact that I've processed umpteen thousand jobs and some less-than-umpteen thousand number failed does me no good. What I really need to see (and alert on) is that my SyncFooJob has failed > 5% of attempts in the past 5 minutes.

**Comment by mperham** [comment]
I'd love input, add as much detail as you'd like! The stats will likely look similar to the metrics already put out by Sidekiq, review these pages:

https://github.com/mperham/sidekiq/wiki/Pro-Metrics
https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics

Another popular alert is if the latency of a queue goes beyond a certain point (i.e. the queue backs up).

The INFO command has changed since that wiki content was authored, it has queue sizes now.

**Comment by pbrisbin** [comment]
> The stats will likely look similar to the metrics already put out by Sidekiq

Oh, that's actually a perfect description of our needs. Recreating alerts I had previously through Sidekiq's Statsd outlet is exactly what I'm trying to do here.

**Comment by jdreaver** [comment]
Hey @mperham, it looks like you are already implementing this, which is awesome! https://github.com/contribsys/faktory/wiki/Pro-Metrics

I see that you have a metric for queue size. Is it possible to add a metric for the age of the oldest item in a job queue? If that's possible, we would get Faktory Pro in a heartbeat, because then we can move some jobs that live in Postgres queues to Faktory without losing some of our metrics/alerts on these queues.

**Comment by mperham** [comment]
@jdreaver The issue is that calculating the queue latency is quite a bit heavier-weight than the queue size.  If you have dozens of queues, this adds up.  WDYT about providing an array of queue names for which you want to monitor latency?

```
[statsd]
  location = ...
  queueLatency = [ 'critical', 'default', 'low']
```

**Comment by jdreaver** [comment]
That looks like a fine solution and would work great for us. :+1:

**Comment by mperham** [comment]
Will be in the next release!
