### ISSUE TITLE
Add travis ?

### ISSUE THREAD

**Issue by agnivade** [contribsys/faktory#23]
Adding it should be as simple as running the build.sh I believe. But, it doesn't need to install the Go distribution because if we specify the language in travis, it automatically contains Go.

So, we just need to install rocks db and then run the tests.

Also, adding go vet and go lint will be good. Though that is a separate task.

**Comment by andrewstucki** [comment]
From the looks of it the rocksdb build isn't going to be as simple as running `build.sh`. It looks like the static rocksdb build on the VM gets built without compression support so that the static linking is going to work with contribsys/gorocksdb.

https://github.com/facebook/rocksdb/blob/master/build_tools/build_detect_platform seems to enable compression if it finds zlib or libbz2 headers, which are both on travis build machines by default.

That, plus travis does some crazy stuff with branch builds that breaks go path-based dependency resolution. I have a branch going to see if I can hash all that stuff out though.

**Comment by agnivade** [comment]
Ah I see. Thanks for looking into it.

**Comment by mperham** [comment]
Moving to #24
