### ISSUE TITLE
Set default reserve_for

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#267]
It would be good if we could set the default reserve_for on the server side, instead of on every single job. We are migrating from Sidekiq, and for now, having a higher reserve_for would be good for us, since worker crashes are pretty rare.

**Comment by scottrobertson** [comment]
Out of interest, what type of crash would cause Faktory the job to become stuck? We never see any sidekiq processes actually "crash", so we should be pretty safe to set this high for now?

**Comment by mperham** [comment]
A crash or deadlock is typically due to a MRI or native gem bug.  For instance, therubyracer gem has a threading bug that will deadlock Sidekiq or FWR.

You can say that crashes are rare but all it takes is one gem upgrade to surface a new crashing bug. Unfortunately there's no right answer or default value but we should be able to make this configurable.

Note that you can set the default for all FWR jobs here:

https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory.rb#L36

That might be a better idea if you want different values for different worker types (i.e. Go vs Ruby).

**Comment by mperham** [comment]
I'm going to back off this for now.  I'm not sure it's a good idea to have a config knob at the Faktory level, it's likely better to have a knob that is specific to each worker package you use, i.e. Ruby jobs should have a different value than Go jobs.
