### ISSUE TITLE
Reaped lingering connections

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#273]
Have a problem with long-running jobs. After about 15 minutes, this keeps happening which then leaves the worker running, but the worker disappears from the UI. The job is still active, as it has a long reserve_for. 

Any suggestions on how to debug? Why would the worker stop sending a heartbeat?

```
E 2020-01-18T16:26:30.595Z error=read tcp 10.42.5.47:7419->10.42.6.185:43966: use of closed network connection Unexpected socket error
W 2020-01-18T16:26:30.595Z Reaped 1 lingering connections, this is a sign your workers are having problems
W 2020-01-18T16:26:30.595Z All worker processes should send a heartbeat every 15 seconds
```

**Comment by mperham** [comment]
Some environments have an aggressive firewall policy which kills quiet TCP connections after N minutes.  To work around this, it is common to enable TCP Keep-Alives on a socket, which is done here:

https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory/client.rb#L213

The only other thing I can think of is your worker threads starving for CPU time (e.g. a thread holds MRI's GVL for many seconds, which shouldn't be possible) so that the BEAT thread doesn't run for a minute. Faktory kills any worker that doesn't send a heartbeat within 60 seconds.

**Comment by mperham** [comment]
Add logging to `Faktory::Client#beat` is the best thing I can think of.

**Comment by scottrobertson** [comment]
@mperham will do, thanks. Not seen this in a while, so i think it's safe to assume it was a CPU starving issue.
