### ISSUE TITLE
go get install wrong version

### ISSUE THREAD

**Issue by alexio777** [contribsys/faktory#288]
Hello.

I have use go 1.13
When I do go get github.com/contribsys/faktory it install the old version v0.5.0
And when I do go get github.com/contribsys/faktory@master it install latest version but the result is a compilation error:
go build
github.com/contribsys/faktory: package provided by github.com/contribsys/faktory at latest version v0.5.0 but not at required version v1.2.0-1.0.20200221202541-1e7510a7f17d

**Comment by mperham** [comment]
I don't use `go get` so I'm not sure what's wrong.  Can you use modules and specify the version tag?

**Comment by DavidLarsKetch** [comment]
For anyone's edification, I ran into this as well, and @mperham advice to specify version tag is the best approach. The reason go does this is because all version tags in this repo utilize a pre-release (e.g., `v1.4.1-1`, the `-1` being the pre-release part). `go get` looks for a full release and the only one existing in this repo is `v0.5.0`. Only if it can't find a full release in the repo will it look at pre-releases. Hence, being specific with a version tag is the best approach.

@mperham if there's a reason to keep the pre-release versioning, then no need to change anything to satisfy Go's quirks. Alternatively, if there's no good reason to keep the pre-release, then having a more recent full release (e.g., `v1.4.2`) may eliminate a little confusion.

**Comment by mperham** [comment]
Faktory’s versioning comes from Debian which uses the trailing -1 to version the packaging; if you make package fixes you can repackage the same 1.4.2 binary with -2, -3, etc.

Not sure if it is worth continuing this style of version or not.

**Comment by DavidLarsKetch** [comment]
Goodness, just saw: #318 The change there should prevent any further issues.

**Comment by spellgen** [comment]
afaik `go get -u ...` is the blessed way to do version updates on go imports
