### ISSUE TITLE
Is Faktory more performant than sidekiq?

### ISSUE THREAD

**Issue by dorongutman** [contribsys/faktory#315]
Since faktory is implemented in go and runs independently from the code itself, is it more performant than sidekiq when comparing the same ruby worker?
Comparing sidekiq enterprise to faktory enterprise - Is it more reliable (compared to sidekiq) in not losing jobs, throttling, scheduling, unique jobs, etc. ?

**Comment by mperham** [comment]
This is like asking "is mysql faster than postgres?" Too many variables, one feature might be faster, another might be slower.

In general, Faktory should be more reliable because you are not restarting it every N hours like Sidekiq. I find that, in practice, most job loss occurs at deploy time due to unsafe restart.

Sidekiq does not provide any throttling, only Faktory Enterprise provides real throttling.
