### ISSUE TITLE
Highly Available Faktory

### ISSUE THREAD

**Issue by sloan-dog** [contribsys/faktory#368]
Faktory can be backed by a remote instance of redis. This prevents data loss in the case of faktory dying.
However, jobs cannot be processed in the meantime, as the single instance of faktory is dead. 

Multiple instances of faktory were backed by the same redis instance, configured as a quorum, to facilitate high availability. E.g. If configured in a raft and the leader dies, the remaining members of quorum can elect new leader and jobs can be processed.

**Comment by mperham** [comment]
There are a number of features which are not designed to handle multiple instances writing to a single Redis so that's unlikely to ever happen. And many features are written assuming one Faktory only, for instance you can't split batch jobs or throttle queues across Faktory instances.

You can run multiple Faktorys and have the client handle network errors, e.g. one Faktory per datacenter and fail over to a backup datacenter when necessary. It's possible you could even use an HAProxy instance to automate this failover without any client work at all. But all of this extra logic and infrastructure would make the system arguably less reliable, not more. Only you can determine what's right for your organization and needs.

**Comment by sloan-dog** [comment]
In ole faktory gitter, it was suggested that you'd explored running multiple instances of faktory before. It sounds like maybe that isn't possible.
