### ISSUE TITLE
Faktory Work Protocol specification

### ISSUE THREAD

**Issue by ghilesmeddour** [contribsys/faktory#378]
Hi,

I am implementing a Faktory client in Python, I have some simple questions about [Faktory Work Protocol](https://github.com/contribsys/faktory/blob/master/docs/protocol-specification.md) :)

- [Why the field `created_at` is not considered as read-only ?](https://github.com/contribsys/faktory/blob/master/docs/protocol-specification.md#optional-fields)
- [END seems not to return an OK](https://github.com/contribsys/faktory/blob/master/docs/protocol-specification.md#beat-command) (#376)
- I'm not sure about the validity of certain commands for certain states. I have added [this summary table](https://github.com/contribsys/faktory/pull/377/commits/294d1aa0b18d1397ee1e1c6b1498cd174107aadd), can you confirm that it corresponds to the specifications.

Thanks

**Comment by mperham** [comment]
created_at is not considered read only because it is supplied by the client. It's informative only and isn't used by Faktory internally.

The connection state should be straightforward:

* The HELLO and HI handshake establish the authenticated connection
* Client can then issue any "typical" runtime commands
* Client can tear down the connection with END
