### ISSUE TITLE
Label CSS missing in new Bootstrap

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#383]
Looks like the Bootstrap 5 upgrade by @saurori might have excluded the label classes. I see something called badges in v5 but I don't see the semantic classes like `label-info`, `label-danger`, etc which we used for coloring purposes.

https://getbootstrap.com/docs/3.4/components/#labels

In this image, the "golang-1.5.0" text should be in a colored box.

<img width="603" alt="Screen Shot 2021-10-06 at 11 37 19 AM" src="https://user-images.githubusercontent.com/2911/136263591-aeea8099-3854-47dc-9334-0da9e3dd8bd7.png">

Help?

**Comment by saurori** [comment]
Yeah they need to be replaced with badges with a background color.

So for example `label-info` -> `badge bg-info`. Or `label-danger` -> `badge bg-danger`

See: https://getbootstrap.com/docs/5.1/components/badge/#background-colors

I can make a PR later or tomorrow. Otherwise it should be an easy fix for you or someone else to handle.
