### ISSUE TITLE
Rethinking TLS/SSL requirements

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#64]
Right now Faktory requires TLS by default if not listening explicitly on "localhost".  This ignores modern development practices like containers with host-only networking where the service in the container is listening on non-localhost but is still effectively local.

Instead ignore the network binding and rely on the environment flag:

* `-e development` means we don't require TLS by default.  We'll still check the TLS directory for certs and use them if possible.
* `-e production` means we require TLS by default.  The user can pass -no-tls otherwise we exit early if TLS certs aren't found.

How do we ensure that people actively enable the production flag when in production?  Should it be the default and we force people to enable development?

Clients should use "tcp+tls" for the protocol if they want TLS `tcp+tls://192.168.1.1:7419` or "tcp" for an unencrypted connection.  This feels ugly and alternative suggestions are welcome.

Is sharing the same port between TLS and non-TLS sockets a bad idea?  Should we be using 7419 for plain sockets and 7443 for TLS sockets, to make the security setup more explicit?

**Comment by mperham** [comment]
This is an alternative approach: rip out all TLS support and force the customer to integrate TLS themselves if they want encrypted traffic:

https://blog.codeship.com/using-honcho-create-multi-process-docker-container/

**Comment by cdrx** [comment]
I think TLS is important, but the way its implemented now being tightly coupled to hostname (if `localhost` or not) and password is confusing.

Configuring workers that run on the same machine as faktory is a pain if you also have workers running on a different machine, because you cant TLS a connection to `localhost`, so you have to configure them to connect to the external hostname.

I think the ideal solution would be opportunistic TLS, ala `STARTTLS` in SMTP etc. So faktory would listen on a single port, but offer workers a way to enable TLS if its configured on the server. 

If the server sent a `HI` with `{"v": "2", "tls": true}` then the worker could (optionally) choose to upgrade that connection to TLS by sending a `STARTTLS` response, before sending the password back. 

`-e production` could choose to require TLS and should probably be the default.

**Comment by mperham** [comment]
Great idea on STARTTLS, I like it.

**Comment by cdrx** [comment]
Do we need to worry about worker backwards compatibility at this point? 

If faktory uses opportunistic TLS then all initial connections would be plaintext, but existing worker implementations expect to send TLS if password supplied and host != localhost, so they would likely break.

**Comment by mperham** [comment]
We should make an effort to keep compatibility for one version back and have a migration path.  Version 2 should ideally still support version 1 syntax.  Version 3 can break version 1. This gives the worker libraries time to upgrade.

If the server advertises a newer HI protocol version, the worker should advise an upgrade to the user and do its best to proceed.  I can live with breaking stuff right now, but we need to be much more careful six months from now when the community is larger.

**Comment by mperham** [comment]
TLS removed, recommendation today is to put stunnel or spiped in front of it in a container.
