### ISSUE TITLE
Handling poison pills?

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#99]
A poison pill is a job which causes the worker process to crash.  This will lead to the job being retried every hour (by default) when the job reservation times out, forever.  How do we catch and prevent this?  Should reservation recovery increment Job.Failure.RetryCount and follow the retry logic?  Can we detect a poison pill and move it to the Dead set immediately?

**Comment by jweslley** [comment]
There is another situation to consider: some jobs can take longer than expected to finish (due to unexpected reasons, third-party integrations, bad evaluation for `reserve_for` parameter, ...).  In these cases, a worker can be executing two or more instances of the same job.  What can we avoid running multiple instances? Is it a faktory design decision or a job's developer one?

**Comment by mperham** [comment]
Yeah, that's a problem.  One heuristic is to see if the associated worker heartbeat is still alive when the job times out but even that has edge cases.  Workers that don't FAIL long-running jobs upon shutdown can appear like poison pills.

**Comment by andrewstucki** [comment]
@jweslley I'm not sure you can really fully prevent workers from behaving badly and introducing things that cause something like double-processing. My first thought is that, like any sort of distributed system you should probably be putting in idempotency guarantees for jobs so that you can handle generalized at-least once processing.

Regarding poison pills, incrementing some sort of failure count and permanently failing jobs once the count reaches a certain threshold makes sense to me. Not sure if that should be separate from RetryCount or lumped into it, but I think that it would probably be easier just to tie them together and I can't think of a super-good reason for separating how faktory treats a failure that causes a retry and a timeout that causes a retry.

**Comment by mperham** [comment]
I think the consensus is that jobs which are unacknowledged and time out should use the retry process as if FAIL were called without any error data.  This will allow exponential backoff if retries are enabled.  If retries are disabled, the job can be discarded as with a normal FAIL.
